// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oibffpzcdqfixapubmgj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9pYmZmcHpjZHFmaXhhcHVibWdqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwMzA5MzMsImV4cCI6MjA2MDYwNjkzM30.9X2I58EsuvXT1alZqz7HFrrNEcKjjzVScaEjaxlxuvE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);